// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK8pHR66dH6FvyMgvyGhta8kh9PZR7-HY',
    appId: '1:682188599088:web:8e8cadcb75aa681cdde2f5',
    messagingSenderId: '682188599088',
    projectId: 'primeform-app',
    authDomain: 'primeform-app.firebaseapp.com',
    storageBucket: 'primeform-app.firebasestorage.app',
    measurementId: 'G-W9SKDLH5BJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkdILt8ih6IQrqeQ-RbdYRqNN2MgFEOlo',
    appId: '1:682188599088:android:de2c7cba5dfed4cedde2f5',
    messagingSenderId: '682188599088',
    projectId: 'primeform-app',
    storageBucket: 'primeform-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEufH9_L_nvBA7B4QikyuW5-bs95V141E',
    appId: '1:682188599088:ios:8f3f51142c7682e1dde2f5',
    messagingSenderId: '682188599088',
    projectId: 'primeform-app',
    storageBucket: 'primeform-app.firebasestorage.app',
    iosBundleId: 'com.example.primeformApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEufH9_L_nvBA7B4QikyuW5-bs95V141E',
    appId: '1:682188599088:ios:8f3f51142c7682e1dde2f5',
    messagingSenderId: '682188599088',
    projectId: 'primeform-app',
    storageBucket: 'primeform-app.firebasestorage.app',
    iosBundleId: 'com.example.primeformApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK8pHR66dH6FvyMgvyGhta8kh9PZR7-HY',
    appId: '1:682188599088:web:af12b46729342befdde2f5',
    messagingSenderId: '682188599088',
    projectId: 'primeform-app',
    authDomain: 'primeform-app.firebaseapp.com',
    storageBucket: 'primeform-app.firebasestorage.app',
    measurementId: 'G-3ZP57RT50K',
  );
}
